project:
  type: book
  output-dir: docs

book:
  title: "Bio724D"
  author: "Paul M. Magwene and Gregory A. Wray"
  date: "2023"
  chapters:
    - index.qmd
    - part: "Computing Basics"
      chapters:
      - Computing_basics/local-computing.qmd
      - Computing_basics/remote-computing.qmd
    - part: "R"
      chapters:
      - R-getting-started.qmd
      - R-intro-RMarkdown.qmd
      - R-dplyr-intro.qmd
      - R-ggplot-intro.qmd
      - references.qmd
    - part: "Unix"
      chapters:
      - Unix/Unix-bash.qmd
      - Unix/Unix-awk.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

editor: visual

